# Generated by Django 5.2 on 2025-10-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("EMPLOYMENT", "Umowa o pracę"),
                            ("MANDATE", "Umowa zlecenie"),
                            ("TASK", "Umowa o dzieło"),
                            ("BUSINESS", "Własna działalność gospodarcza"),
                            ("B2B", "Umowa B2B"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "zus_percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="Procent składki ZUS", max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ umowy",
                "verbose_name_plural": "Typy umów",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Wiek")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Mężczyzna"), ("K", "Kobieta")],
                        max_length=1,
                        verbose_name="Płeć",
                    ),
                ),
                (
                    "salary_gross",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Wynagrodzenie brutto",
                    ),
                ),
                (
                    "work_start_year",
                    models.IntegerField(verbose_name="Rok rozpoczęcia pracy"),
                ),
                (
                    "planned_retirement_year",
                    models.IntegerField(
                        verbose_name="Planowany rok przejścia na emeryturę"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil użytkownika",
                "verbose_name_plural": "Profile użytkowników",
            },
        ),
        migrations.CreateModel(
            name="RetirementCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_pension",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Obliczona emerytura",
                    ),
                ),
                (
                    "total_contributions",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Suma składek"
                    ),
                ),
                (
                    "life_expectancy_months",
                    models.IntegerField(
                        verbose_name="Dalsze trwanie życia w miesiącach"
                    ),
                ),
                ("calculation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to="simulator.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obliczenie emerytury",
                "verbose_name_plural": "Obliczenia emerytur",
                "ordering": ["-calculation_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.IntegerField(verbose_name="Rok rozpoczęcia")),
                ("end_year", models.IntegerField(verbose_name="Rok zakończenia")),
                (
                    "salary_gross_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Wynagrodzenie brutto miesięczne",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulator.contracttype",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_periods",
                        to="simulator.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Okres pracy",
                "verbose_name_plural": "Okresy pracy",
                "ordering": ["start_year"],
            },
        ),
    ]
